spring.application.name=shortlink

spring.datasource.url=jdbc:postgresql://localhost:5432/shortlink
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true

security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
security.jwt.expiration-time=86400000

app.base-url=http://localhost:3000


spring.mail.host=smtp.hostinger.com
spring.mail.port=587
spring.mail.username=no-reply@tremz.in
spring.mail.password=@MinasGerais10

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Swagger / OpenApi
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true
springdoc.packages-to-scan=br.com.lucas.shortlink.controllers